baseURL = 'https://blog.allia.dev/'
languageCode = 'es'
title = 'Allia Studio Blog'
theme = 'allia-theme'

# Build settings
enableRobotsTXT = true
enableGitInfo = true

[params]
  description = "Tech insights y tendencias para empresas que quieren crecer con tecnologia"
  author = "Allia Studio"
  mainSections = ["posts"]
  showReadingTime = true
  showDate = true
  showAuthor = true

  [params.social]
    github = "https://github.com/allia-studio"
    twitter = "https://twitter.com/alliastudio"
    rss = true

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "/posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "external"
    name = "allia.dev"
    url = "https://allia.dev"
    weight = 2

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
